export const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_OWNERSHIP_DENIED: 'RESOURCE_OWNERSHIP_DENIED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // AI
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',

  // Device
  DEVICE_AUTH_FAILED: 'DEVICE_AUTH_FAILED',
  DEVICE_RECIPIENT_NOT_FOUND: 'DEVICE_RECIPIENT_NOT_FOUND',

  // System
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RECIPIENT_LIMIT_EXCEEDED: 'RECIPIENT_LIMIT_EXCEEDED',

  // Patient binding (Section 1: caregiver invites patient by email to a Recipient)
  PATIENT_USER_NOT_FOUND: 'PATIENT_USER_NOT_FOUND',
  PATIENT_USER_ROLE_MISMATCH: 'PATIENT_USER_ROLE_MISMATCH',
  PATIENT_USER_ALREADY_BOUND: 'PATIENT_USER_ALREADY_BOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  AUTH_REQUIRED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_OWNERSHIP_DENIED: 403,
  VALIDATION_ERROR: 400,
  DUPLICATE_ENTRY: 409,
  INVALID_STATE_TRANSITION: 400,
  RATE_LIMIT_EXCEEDED: 429,
  AI_GENERATION_FAILED: 502,
  AI_RATE_LIMITED: 429,
  AI_INVALID_RESPONSE: 502,
  FILE_TOO_LARGE: 400,
  FILE_INVALID_TYPE: 400,
  DEVICE_AUTH_FAILED: 401,
  DEVICE_RECIPIENT_NOT_FOUND: 404,
  SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  RECIPIENT_LIMIT_EXCEEDED: 400,
  PATIENT_USER_NOT_FOUND: 404,
  PATIENT_USER_ROLE_MISMATCH: 400,
  PATIENT_USER_ALREADY_BOUND: 409,
};
